version: '3.8'

services:
  db:
    image: postgres:14
    container_name: postgres
    environment:
      POSTGRES_USER: morafea
      POSTGRES_PASSWORD: RealMadrid#15
      POSTGRES_DB: morafea
    volumes:
      - db_data:/var/lib/postgresql/data
    networks:
      - app-network
    ports:
      - "5433:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U morafea" ]
      interval: 5s
      timeout: 5s
      retries: 5

  migration:
    build:
      context: .
      dockerfile: docker/migration/Dockerfile
    environment:
      DB_HOST: db
      DB_USER: morafea
      DB_PASSWORD: RealMadrid#15
      DB_NAME: morafea
      DB_PORT: 5432
      SERVICE: migration
    depends_on:
      db:
        condition: service_healthy
    restart: "on-failure"
    networks:
      - app-network

  customers_app:
    build:
      context: .
      dockerfile: docker/customer/Dockerfile
    container_name: go-customer-app
    ports:
      - "8080:8080"
    environment:
      DB_HOST: db
      DB_USER: morafea
      DB_PASSWORD: RealMadrid#15
      DB_NAME: morafea
      DB_PORT: 5432
      PORT: 8080
      SERVICE: customers
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - app-network

  sellers_app:
    build:
      context: .
      dockerfile: docker/seller/Dockerfile
    container_name: go-sellers-app
    ports:
      - "8081:8081"
    environment:
      DB_HOST: db
      DB_USER: morafea
      DB_PASSWORD: RealMadrid#15
      DB_NAME: morafea
      DB_PORT: 5432
      PORT: 8081
      SERVICE: sellers
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - app-network


  admin_app:
    build:
      context: .
      dockerfile: docker/admin/Dockerfile
    container_name: go-admin-app
    ports:
      - "8082:8082"
    environment:
      DB_HOST: db
      DB_USER: morafea
      DB_PASSWORD: RealMadrid#15
      DB_NAME: morafea
      DB_PORT: 5432
      PORT: 8082
      SERVICE: admins
    depends_on:
      db:
        condition: service_healthy
      migration:
        condition: service_completed_successfully
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
